# Generated by Django 5.2 on 2025-04-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # Reemplaza con la dependencia correcta, si la hay
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('orientacion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
    ]