# Generated by Django 5.2 on 2025-04-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad de pasajeros')),
                ('orientacion', models.CharField(max_length=50, verbose_name='Orientación')),
            ],
        ),
    ]
