# Generated by Django 3.2 on 2025-06-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={},
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='capacidad',
            field=models.PositiveIntegerField(verbose_name='Capacidad de pasajeros'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='orientacion',
            field=models.CharField(max_length=50, verbose_name='Orientación'),
        ),
    ]
